#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Nov 16 19:33:59 ART 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Mellow Shader v2.2.zip
